backend:
  name: github
  repo: lsolesen/madsdavidsen-com-jekyll
  branch: master # Branch to update (optional; defaults to master)

media_folder: "assets/images/uploads" # Media files will be stored in the repo under images/uploads

site_url: https://madsdavidsen.com
display_url: https://madsdavidsen.com
logo_url: https://madsdavidsen.com/android-chrome-144x144.png

show_preview_links: true

editor:
  preview: false

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    editor:
      preview: false
    label: "Blog" # Used in the UI
    label_singular: 'Post'
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    view_groups:
      - label: Year
        field: last_modified_at
        # groups items based on the value matched by the pattern
        pattern: \d{4}
    sortable_fields: ['title', 'last_updated_on', 'commit_date']
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Category", name: "category", widget: "select", options: ["Daily life", "Columns", "Media"]}
      - {label: "Excerpt", name: "excerpt", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "TOC", name: "toc", widget: "select", options: ["", "true", "false"], required: false}
      - {label: "Last modified at", name: "last_modified_at", widget: "datetime", format: "YYYY-MM-DDThh:mm:ssZ", dateFormat: "DD-MM-YYYY", timeFormat: "HH:mm", required: false}
      - {label: "Language", name: "language", widget: "select", options: ["en", "da"]}
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    editor:
      preview: false
    label: "Pages" # Used in the UI
    folder: "_pages/" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "SEO Title", name: "seo_title", widget: "string", required: false}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Excerpt", name: "excerpt", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Header"
        name: "header"
        widget: "object"
        required: false
        fields:
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Alt", name: "alt", widget: "string", required: false}
      - {label: "Author profile", name: "author_profile", widget: "select", options: ["true", "false"]}
      - {label: "Last modified at", name: "last_modified_at", widget: "datetime", format: "YYYY-MM-DDThh:mm:ssZ", dateFormat: "DD-MM-YYYY", timeFormat: "HH:mm", required: false}
      - {label: "Layout", name: "layout", widget: "select", options: ["single", "posts", "category", "categories", "tags"], default: "single"}
      - {label: "Taxonomy", name: "taxonomy", widget: "hidden"}
  - label: "Frontpage"
    name: "frontpage"
    editor:
      preview: false
    files:
      - label: "Forsiden"
        name: "index"
        file: "index.html"
        fields: # The fields for each document, usually in front matter
          - {label: "Title", name: "title", widget: "string"}
          - {label: "SEO Title", name: "seo_title", widget: "string", required: false}
          - {label: "Excerpt", name: "excerpt", widget: "string", required: true}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: Header Image
            name: feature_row_header_image
            widget: list
            collapsed: true
            required: false
            fields:
              - {label: "Image", name: "image_path", widget: "string", required: false}
              - {label: "Alt", name: "alt", widget: "string", required: false}
          - label: Intro
            name: intro
            widget: list
            collapsed: true
            required: false
            fields:
              - {label: "Exerpt", name: "excerpt", widget: "text", required: false}
              - {label: "Image", name: "image_path", widget: "string", required: false}
              - {label: "Alt", name: "alt", widget: "string", required: false}
          - label: Book
            name: book
            widget: list
            collapsed: true
            required: false
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Image", name: "image_path", widget: "string", required: false}
              - {label: "Alt", name: "alt", widget: "string", required: false}
              - {label: "Exerpt", name: "excerpt", widget: "text", required: false}
              - {label: "Url", name: "url", widget: "string", required: false}
              - {label: "Btn label", name: "btn_label", widget: "string", required: false}
              - {label: "Btn class", name: "btn_class", widget: "select", options: ["", "btn--success", "btn--warning", "btn--danger", "btn--info"], default: "", required: false}
          - label: Feature row
            name: feature_row
            widget: list
            collapsed: true
            required: false
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Image", name: "image_path", widget: "string", required: false}
              - {label: "Alt", name: "alt", widget: "string", required: false}
              - {label: "Exerpt", name: "excerpt", widget: "text", required: false}
              - {label: "Url", name: "url", widget: "string", required: false}
              - {label: "Btn label", name: "btn_label", widget: "string", required: false}
              - {label: "Btn class", name: "btn_class", widget: "select", options: ["", "btn--success", "btn--warning", "btn--danger", "btn--info"], default: "", required: false}
          - label: World Map
            name: feature_row_world_map
            widget: list
            collapsed: true
            required: false
            fields:
              - {label: "Image", name: "image_path", widget: "string", required: false}
              - {label: "Alt", name: "alt", widget: "string", required: false}
          - label: Blog link
            name: blog
            widget: list
            collapsed: true
            required: false
            fields:
              - {label: "Exerpt", name: "excerpt", widget: "text", required: false}
          - label: Media link
            name: media
            widget: list
            collapsed: true
            required: false
            fields:
              - {label: "Exerpt", name: "excerpt", widget: "text", required: false}
          - {label: "Layout", name: "layout", widget: "select", options: ["splash"], default: "splash"}
          - {label: "Last modified at", name: "last_modified_at", widget: "datetime", format: "YYYY-MM-DDThh:mm:ssZ", dateFormat: "DD-MM-YYYY", timeFormat: "HH:mm", required: false}
  - label: "Navigation"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation Menu"
        name: nav
        file: "_data/navigation.yml"
        fields:
          - label: "Nav Items"
            label_singular: "Nav Item"
            name: main
            widget: list
            fields:
              - {label: "Display Text", name: title, widget: string}
              - {label: URL, name: url, widget: string}
          - label: "Shortcuts"
            label_singular: "Shortcut"
            name: sidebar
            widget: list
            fields:
              - {label: "Display Text", name: title, widget: string}
              - {label: "URL", name: url, widget: string, required: false}
              - label: "Links"
                name: children
                widget: list
                fields:
                  - {label: "Display Text", name: title, widget: string}
                  - {label: "URL", name: url, widget: string, required: false}
